# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp
  
  # a Simple github library to implemenst a progress HUD (Activity indicator).
  pod 'PKHUD', '~> 5.0' #https://github.com/pkluz/PKHUD
end
